Bug fix #1
Issue: Can't view database classes in admin view.
Error: 'super' object has no attribute 'dicts'
Cause: Deprecated allauth code in settings.py, due to version conflict.